server:
  port: 9000
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/olx-monitor"

spring:
  application:    name: auth-service  zipkin:    base-url: http://localhost:9411  config:    import: configserver:http://localhost:8888
eureka:
  client:
     register-with-eureka: true
     fetch-registry: true
